course_mock_data = [
 {'department_abbrev': 'CSE',
  'course_number': 142,
  'course_college': "College of Engineering",
  'long_course_title': "Fundamentals of Programming",
  "course_branch": 0,
  "course_cat_omit": False,
  "diversity_crs": False,
  "english_comp": True,
  "social_science": False,
  "natural_science": True,
  "rsn": False,
  "arts_hum": False,
  "writing_crs": False,
  "min_qtr_credits": 1,
  "max_qtr_credits": 5},
 {'department_abbrev': 'BIO',
  'course_number': 101,
  'course_college': "Col of Arts & Sci",
  'long_course_title': "Intoduction to Biology",
  "course_branch": 1,
  "course_cat_omit": True,
  "diversity_crs": False,
  "english_comp": False,
  "social_science": False,
  "natural_science": True,
  "rsn": True,
  "arts_hum": False,
  "writing_crs": False,
  "min_qtr_credits": 5,
  "max_qtr_credits": 5},
 {"department_abbrev": "A A",
  "course_number": 101,
  "course_college": "J",
  "long_course_title": "Air and Space Vehicles",
  "course_branch": 0,
  "course_cat_omit": False,
  "diversity_crs": False,
  "english_comp": False,
  "social_science": False,
  "natural_science": True,
  "rsn": False,
  "arts_hum": False,
  "writing_crs": False,
  "min_qtr_credits": 2,
  "max_qtr_credits": 5},
 {"department_abbrev": "BIO",
  "course_number": 103,
  "course_college": "J",
  "long_course_title": "Into to Bio",
  "course_branch": 0,
  "course_cat_omit": False,
  "diversity_crs": False,
  "english_comp": False,
  "social_science": False,
  "natural_science": True,
  "rsn": False,
  "arts_hum": False,
  "writing_crs": False,
  "min_qtr_credits": 1,
  "max_qtr_credits": 5},
 {"department_abbrev": "CHEM",
  "course_number": 142,
  "course_college": "J",
  "long_course_title": "Intro to chem",
  "course_branch": 0,
  "course_cat_omit": False,
  "diversity_crs": False,
  "english_comp": False,
  "social_science": False,
  "natural_science": True,
  "rsn": False,
  "arts_hum": False,
  "writing_crs": False,
  "min_qtr_credits": 4,
  "max_qtr_credits": 5},
]
