version: '3.4'

services:
  app:
    build:
      context: .
      target: app-container
    restart: always
    container_name: dawgpath_pipeline_admin_app
    environment:
      - GOOGLE_ANALYTICS_KEY=${GOOGLE_ANALYTICS_KEY}
    volumes:
      - ./dawgpath_pipeline_admin:/app/dawgpath_pipeline_admin
      - statics-volume:/static
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
    stdin_open: true
    tty: true
  node-bundler:
    build:
      context: .
      target: node-bundler
    restart: always
    container_name: dawgpath_pipeline_admin_node
    ports:
      - "${BUNDLE_ANALYZER_PORT:-8888}:8888" # Required when environment.BUNDLE_ANALYZER is true
    environment:
      NODE_ENV: "development"
      VUE_DEVTOOLS: "True"
      BUNDLE_ANALYZER: "True"
    volumes:
      - ./dawgpath_pipeline_admin:/app/dawgpath_pipeline_admin # expose main django app so vite can output bundles here
      - ./dawgpath_pipeline_admin_vue:/app/dawgpath_pipeline_admin_vue
      - statics-volume:/static
    command: npm run watch
    stdin_open: true
    tty: true
volumes:
  statics-volume:
