"""adding registration table

Revision ID: 050ceb9cab20
Revises: e14a2aa4b6ff
Create Date: 2021-06-29 00:42:04.118614+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050ceb9cab20'
down_revision = 'e14a2aa4b6ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_key', sa.Integer(), nullable=True),
    sa.Column('regis_yr', sa.SmallInteger(), nullable=True),
    sa.Column('regis_qtr', sa.SmallInteger(), nullable=True),
    sa.Column('crs_curric_abbr', sa.String(length=6), nullable=True),
    sa.Column('crs_number', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration')
    # ### end Alembic commands ###
