"""adding combined qtr to regis major

Revision ID: 084e00d17022
Revises: 4c2187d87495
Create Date: 2021-07-22 19:20:28.056548+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084e00d17022'
down_revision = '4c2187d87495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regismajor', sa.Column('regis_term', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regismajor', 'regis_term')
    # ### end Alembic commands ###
