"""update major credential desc

Revision ID: 140915d317a6
Revises: 8cf3c0cf9e93
Create Date: 2021-12-17 23:58:35.199438+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140915d317a6'
down_revision = '8cf3c0cf9e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
