"""Adding combined qtr to transcript table

Revision ID: 1aff60cab99f
Revises: 3488dd3245ec
Create Date: 2021-07-15 01:24:00.020195+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aff60cab99f'
down_revision = '3488dd3245ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript', sa.Column('combined_qtr', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcript', 'combined_qtr')
    # ### end Alembic commands ###
