"""adding sr_major

Revision ID: 2e2b38a39ee1
Revises: d15f3012e3d0
Create Date: 2021-09-17 23:49:53.198431+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2b38a39ee1'
down_revision = 'd15f3012e3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('srmajor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major_abbr', sa.String(length=6), nullable=True),
    sa.Column('major_home_url', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('srmajor')
    # ### end Alembic commands ###
