"""Adding transcript table

Revision ID: 3488dd3245ec
Revises: 2923086cc014
Create Date: 2021-07-15 00:55:45.277186+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3488dd3245ec'
down_revision = '2923086cc014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_key', sa.Integer(), nullable=True),
    sa.Column('tran_yr', sa.SmallInteger(), nullable=True),
    sa.Column('tran_qtr', sa.SmallInteger(), nullable=True),
    sa.Column('qtr_grade_points', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('qtr_graded_attmp', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript')
    # ### end Alembic commands ###
