"""adding more indexes to registration

Revision ID: 3ea506050525
Revises: 8709db335246
Create Date: 2021-08-06 00:40:13.006702+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea506050525'
down_revision = '8709db335246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_registration_crs_curric_abbr'), 'registration', ['crs_curric_abbr'], unique=False)
    op.create_index(op.f('ix_registration_crs_number'), 'registration', ['crs_number'], unique=False)
    op.create_index(op.f('ix_registration_regis_qtr'), 'registration', ['regis_qtr'], unique=False)
    op.create_index(op.f('ix_registration_regis_yr'), 'registration', ['regis_yr'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_regis_yr'), table_name='registration')
    op.drop_index(op.f('ix_registration_regis_qtr'), table_name='registration')
    op.drop_index(op.f('ix_registration_crs_number'), table_name='registration')
    op.drop_index(op.f('ix_registration_crs_curric_abbr'), table_name='registration')
    # ### end Alembic commands ###
