"""Adding indexes to transcript table

Revision ID: 4c2187d87495
Revises: 7dde63a002a2
Create Date: 2021-07-15 23:41:57.943203+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2187d87495'
down_revision = '7dde63a002a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transcript_combined_qtr'), 'transcript', ['combined_qtr'], unique=False)
    op.create_index(op.f('ix_transcript_qtr_graded_attmp'), 'transcript', ['qtr_graded_attmp'], unique=False)
    op.create_index(op.f('ix_transcript_system_key'), 'transcript', ['system_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_system_key'), table_name='transcript')
    op.drop_index(op.f('ix_transcript_qtr_graded_attmp'), table_name='transcript')
    op.drop_index(op.f('ix_transcript_combined_qtr'), table_name='transcript')
    # ### end Alembic commands ###
