"""adding model

Revision ID: 56444ed89a7d
Revises: abf108a18f79
Create Date: 2021-08-23 20:35:27.663525+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56444ed89a7d'
down_revision = 'abf108a18f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commonmajorforcourse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crs_curric_abbr', sa.String(length=6), nullable=True),
    sa.Column('crs_number', sa.SmallInteger(), nullable=True),
    sa.Column('major_courts', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commonmajorforcourse_crs_curric_abbr'), 'commonmajorforcourse', ['crs_curric_abbr'], unique=False)
    op.create_index(op.f('ix_commonmajorforcourse_crs_number'), 'commonmajorforcourse', ['crs_number'], unique=False)
    op.add_column('registration', sa.Column('course_id', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_registration_course_id'), 'registration', ['course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_course_id'), table_name='registration')
    op.drop_column('registration', 'course_id')
    op.drop_index(op.f('ix_commonmajorforcourse_crs_number'), table_name='commonmajorforcourse')
    op.drop_index(op.f('ix_commonmajorforcourse_crs_curric_abbr'), table_name='commonmajorforcourse')
    op.drop_table('commonmajorforcourse')
    # ### end Alembic commands ###
