"""adding min credits to course

Revision ID: 60a87e072a1c
Revises: e590eb91aed9
Create Date: 2021-09-28 23:45:01.030124+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a87e072a1c'
down_revision = 'e590eb91aed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('min_credits', sa.Float(precision=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'min_credits')
    # ### end Alembic commands ###
