"""cascade course graph deletes

Revision ID: 62eba47fd41b
Revises: 60a87e072a1c
Create Date: 2021-10-19 18:38:14.101924+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62eba47fd41b'
down_revision = '60a87e072a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'min_credits',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=4),
                    existing_nullable=True)
    op.alter_column('course', 'max_credits',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=4),
                    existing_nullable=True)
    op.drop_constraint('graph_course_id_fkey', 'graph', type_='foreignkey')
    op.create_foreign_key(None, 'graph', 'course',
                          ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'graph', type_='foreignkey')
    op.create_foreign_key('graph_course_id_fkey', 'graph',
                          'course', ['course_id'], ['id'])
    op.alter_column('course', 'max_credits',
                    existing_type=sa.Float(precision=4),
                    type_=sa.REAL(),
                    existing_nullable=True)
    op.alter_column('course', 'min_credits',
                    existing_type=sa.Float(precision=4),
                    type_=sa.REAL(),
                    existing_nullable=True)
    # ### end Alembic commands ###
