"""creating_tables

Revision ID: 6fabacab77b1
Revises: 
Create Date: 2021-05-27 03:07:07.000694+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fabacab77b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_abbrev', sa.String(length=6), nullable=True),
    sa.Column('course_number', sa.SmallInteger(), nullable=True),
    sa.Column('course_college', sa.String(length=1), nullable=True),
    sa.Column('long_course_title', sa.String(length=120), nullable=True),
    sa.Column('course_branch', sa.SmallInteger(), nullable=True),
    sa.Column('course_cat_omit', sa.Boolean(), nullable=True),
    sa.Column('diversity_crs', sa.Boolean(), nullable=True),
    sa.Column('english_comp', sa.Boolean(), nullable=True),
    sa.Column('indiv_society', sa.Boolean(), nullable=True),
    sa.Column('natural_world', sa.Boolean(), nullable=True),
    sa.Column('qsr', sa.Boolean(), nullable=True),
    sa.Column('vis_lit_perf_arts', sa.Boolean(), nullable=True),
    sa.Column('writing_crs', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbrev', sa.String(length=6), nullable=True),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('campus', sa.SmallInteger(), nullable=True),
    sa.Column('url', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prereq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_and_or', sa.String(length=1), nullable=True),
    sa.Column('pr_concurrency', sa.String(length=1), nullable=True),
    sa.Column('pr_cr_s', sa.String(length=1), nullable=True),
    sa.Column('pr_grade_min', sa.String(length=2), nullable=True),
    sa.Column('pr_group_no', sa.SmallInteger(), nullable=True),
    sa.Column('pr_seq_no', sa.SmallInteger(), nullable=True),
    sa.Column('department_abbrev', sa.String(length=6), nullable=True),
    sa.Column('course_number', sa.SmallInteger(), nullable=True),
    sa.Column('pr_curric_abbr', sa.String(length=6), nullable=True),
    sa.Column('pr_course_no', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prereq')
    op.drop_table('curriculum')
    op.drop_table('course')
    # ### end Alembic commands ###
