"""adding concurrent course table

Revision ID: 75009df6f13a
Revises: 050ceb9cab20
Create Date: 2021-06-30 01:09:38.052393+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75009df6f13a'
down_revision = '050ceb9cab20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concurrentcourses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=10), nullable=True, unique=True),
    sa.Column('concurrent_courses', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concurrentcourses')
    # ### end Alembic commands ###
