"""Adding regis_major table

Revision ID: 7dde63a002a2
Revises: 1aff60cab99f
Create Date: 2021-07-15 02:24:13.359569+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dde63a002a2'
down_revision = '1aff60cab99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regismajor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_key', sa.Integer(), nullable=True),
    sa.Column('regis_yr', sa.SmallInteger(), nullable=True),
    sa.Column('regis_qtr', sa.SmallInteger(), nullable=True),
    sa.Column('regis_pathway', sa.SmallInteger(), nullable=True),
    sa.Column('regis_branch', sa.SmallInteger(), nullable=True),
    sa.Column('regis_deg_level', sa.SmallInteger(), nullable=True),
    sa.Column('regis_deg_type', sa.SmallInteger(), nullable=True),
    sa.Column('regis_major_abbr', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regismajor')
    # ### end Alembic commands ###
