"""adding major courses table and combined term to registration

Revision ID: 7ef08ed98333
Revises: 8fe22e675e56
Create Date: 2021-08-02 17:41:40.795546+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef08ed98333'
down_revision = '8fe22e675e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commoncoursemajor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major', sa.String(length=6), nullable=True),
    sa.Column('course_counts', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('registration', sa.Column('regis_term', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration', 'regis_term')
    op.drop_table('commoncoursemajor')
    # ### end Alembic commands ###
