"""Adds credential fields to major

Revision ID: 8cf3c0cf9e93
Revises: c98bd76d5ea3
Create Date: 2021-12-17 23:41:34.284301+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf3c0cf9e93'
down_revision = 'c98bd76d5ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('major', sa.Column('credential_title', sa.String(length=300), nullable=True))
    op.add_column('major', sa.Column('credential_code', sa.String(length=25), nullable=True))
    op.add_column('major', sa.Column('credential_description', sa.String(length=2500), nullable=True))
    op.add_column('major', sa.Column('credential_dateStartLabel', sa.String(length=25), nullable=True))
    op.add_column('major', sa.Column('credential_dateEndLabel', sa.String(length=25), nullable=True))
    op.add_column('major', sa.Column('credential_DoNotPublish', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('major', 'credential_DoNotPublish')
    op.drop_column('major', 'credential_dateEndLabel')
    op.drop_column('major', 'credential_dateStartLabel')
    op.drop_column('major', 'credential_description')
    op.drop_column('major', 'credential_code')
    op.drop_column('major', 'credential_title')
    # ### end Alembic commands ###
