"""adding 2yr flag to major gpa decl

Revision ID: 8fe22e675e56
Revises: 084e00d17022
Create Date: 2021-07-30 21:10:40.922464+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe22e675e56'
down_revision = '084e00d17022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('majordecgpadistribution', sa.Column('is_2yr', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('majordecgpadistribution', 'is_2yr')
    # ### end Alembic commands ###
