"""adding student model

Revision ID: abf108a18f79
Revises: dfc0b2307f09
Create Date: 2021-08-23 19:22:11.672313+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf108a18f79'
down_revision = 'dfc0b2307f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_key', sa.Integer(), nullable=True),
    sa.Column('major_abbr', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
