"""Adding major table

Revision ID: bb37cf5b7181
Revises: 90d7a2b0caf9
Create Date: 2021-07-14 01:01:35.838381+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb37cf5b7181'
down_revision = '90d7a2b0caf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_code', sa.String(length=25), nullable=True),
    sa.Column('program_title', sa.String(length=300), nullable=True),
    sa.Column('program_department', sa.String(length=300), nullable=True),
    sa.Column('program_description', sa.Text(), nullable=True),
    sa.Column('program_level', sa.String(length=25), nullable=True),
    sa.Column('program_type', sa.String(length=25), nullable=True),
    sa.Column('program_school_or_college', sa.String(length=300), nullable=True),
    sa.Column('program_dateStartLabel', sa.String(length=25), nullable=True),
    sa.Column('program_dateEndLabel', sa.String(length=25), nullable=True),
    sa.Column('campus_name', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('major')
    # ### end Alembic commands ###
