"""first rev

Revision ID: c12cabff1b2f
Revises: 
Create Date: 2021-05-20 23:02:56.749041+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12cabff1b2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbrev', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('campus', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curriculum')
    # ### end Alembic commands ###
