"""add course

Revision ID: c318b404e55f
Revises: c12cabff1b2f
Create Date: 2021-05-22 04:50:40.494800+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c318b404e55f'
down_revision = 'c12cabff1b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_abbrev', sa.String(), nullable=True),
    sa.Column('course_number', sa.Integer(), nullable=True),
    sa.Column('course_college', sa.Integer(), nullable=True),
    sa.Column('long_course_title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    # ### end Alembic commands ###
