"""Add SWS Course Model

Revision ID: c98bd76d5ea3
Revises: 2c188851747d
Create Date: 2021-11-09 01:37:16.973274+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98bd76d5ea3'
down_revision = '2c188851747d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swscourse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_abbrev', sa.String(length=6), nullable=True),
    sa.Column('course_number', sa.SmallInteger(), nullable=True),
    sa.Column('course_description', sa.Text(), nullable=True),
    sa.Column('offered_string', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swscourse')
    # ### end Alembic commands ###
