"""adding model

Revision ID: d15f3012e3d0
Revises: 56444ed89a7d
Create Date: 2021-08-23 23:57:20.272524+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15f3012e3d0'
down_revision = '56444ed89a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_regismajor_regis_term'), 'regismajor', ['regis_term'], unique=False)
    op.create_index(op.f('ix_regismajor_system_key'), 'regismajor', ['system_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regismajor_system_key'), table_name='regismajor')
    op.drop_index(op.f('ix_regismajor_regis_term'), table_name='regismajor')
    # ### end Alembic commands ###
