"""adding curric graph

Revision ID: e042f20f1db2
Revises: 6aa5ec118959
Create Date: 2021-10-29 22:12:40.026272+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e042f20f1db2'
down_revision = '6aa5ec118959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curricgraph',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('abbrev', sa.String(length=6), nullable=True),
                    sa.Column('graph_json', sa.Text(), nullable=True),
                    sa.Column('create_date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curricgraph')
    # ### end Alembic commands ###
