"""adding max credits to course

Revision ID: e590eb91aed9
Revises: 2e2b38a39ee1
Create Date: 2021-09-28 23:28:28.452336+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e590eb91aed9'
down_revision = '2e2b38a39ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('max_credits', sa.Float(precision=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'max_credits')
    # ### end Alembic commands ###
