"""prereqs

Revision ID: f243e821f0fb
Revises: c318b404e55f
Create Date: 2021-05-27 01:59:12.690864+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f243e821f0fb'
down_revision = 'c318b404e55f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prereq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_and_or', sa.String(length=1), nullable=True),
    sa.Column('pr_concurrency', sa.String(length=1), nullable=True),
    sa.Column('pr_cr_s', sa.String(length=1), nullable=True),
    sa.Column('pr_grade_min', sa.String(length=2), nullable=True),
    sa.Column('pr_group_no', sa.SmallInteger(), nullable=True),
    sa.Column('pr_seq_no', sa.SmallInteger(), nullable=True),
    sa.Column('department_abbrev', sa.String(length=6), nullable=True),
    sa.Column('course_number', sa.SmallInteger(), nullable=True),
    sa.Column('pr_curric_abbr', sa.String(length=6), nullable=True),
    sa.Column('pr_course_no', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prereq')
    # ### end Alembic commands ###
