"""Adding admission type to major

Revision ID: f6bf709a0031
Revises: bb37cf5b7181
Create Date: 2021-07-15 00:17:34.855371+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6bf709a0031'
down_revision = 'bb37cf5b7181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('major', sa.Column('program_admissionType', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('major', 'program_admissionType')
    # ### end Alembic commands ###
