"""adding grade col to registration

Revision ID: f9000a1c2e06
Revises: 75009df6f13a
Create Date: 2021-07-13 00:26:51.993333+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9000a1c2e06'
down_revision = '75009df6f13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration', sa.Column('grade', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration', 'grade')
    # ### end Alembic commands ###
