regis_mock_data = [
    {"system_key": 41,
     "regis_yr": 2016,
     "regis_qtr": 1,
     "regis_pathway": 0,
     "regis_branch": 0,
     "regis_deg_level": 1,
     "regis_deg_type": 1,
     "regis_major_abbr": "MATH  "},
    {"system_key": 41,
     "regis_yr": 2017,
     "regis_qtr": 2,
     "regis_pathway": 0,
     "regis_branch": 0,
     "regis_deg_level": 1,
     "regis_deg_type": 1,
     "regis_major_abbr": "GEOG  "},
    {"system_key": 322,
     "regis_yr": 2020,
     "regis_qtr": 1,
     "regis_pathway": 0,
     "regis_branch": 0,
     "regis_deg_level": 0,
     "regis_deg_type": 0,
     "regis_major_abbr": "N MATR"},
    {"system_key": 527,
     "regis_yr": 2016,
     "regis_qtr": 1,
     "regis_pathway": 0,
     "regis_branch": 0,
     "regis_deg_level": 0,
     "regis_deg_type": 0,
     "regis_major_abbr": "N MATR"},
    {"system_key": 294,
     "regis_yr": 2021,
     "regis_qtr": 2,
     "regis_pathway": 0,
     "regis_branch": 0,
     "regis_deg_level": 0,
     "regis_deg_type": 0,
     "regis_major_abbr": "N MATR"},
    {"system_key": 123,
     "regis_yr": 2016,
     "regis_qtr": 2,
     "regis_pathway": 0,
     "regis_branch": 0,
     "regis_deg_level": 0,
     "regis_deg_type": 0,
     "regis_major_abbr": "N MATR"},
]
