"""adding curric prereqs

Revision ID: 18ed3c223e3d
Revises: e042f20f1db2
Create Date: 2021-11-04 00:50:50.507989+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ed3c223e3d'
down_revision = 'e042f20f1db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
