"""add_sws_freshness_and_remove_unused_tables

Revision ID: 4d49ff73e1e6
Revises: f31ddd9f5ced
Create Date: 2026-09-12 06:25:45.447306+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d49ff73e1e6'
down_revision = 'f31ddd9f5ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swscourse', sa.Column('last_term_fetched', sa.Integer(), nullable=True))
    op.add_column('swscourse', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_commonmajorforcourse_crs_curric_abbr'), table_name='commonmajorforcourse')
    op.drop_index(op.f('ix_commonmajorforcourse_crs_number'), table_name='commonmajorforcourse')
    op.drop_table('commonmajorforcourse')
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swscourse', 'last_updated')
    op.drop_column('swscourse', 'last_term_fetched')
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('system_key', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('major_abbr', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('student_pkey'))
    )
    op.create_table('commonmajorforcourse',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('crs_curric_abbr', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('crs_number', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('major_counts', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('commonmajorforcourse_pkey'))
    )
    op.create_index(op.f('ix_commonmajorforcourse_crs_number'), 'commonmajorforcourse', ['crs_number'], unique=False)
    op.create_index(op.f('ix_commonmajorforcourse_crs_curric_abbr'), 'commonmajorforcourse', ['crs_curric_abbr'], unique=False)
    # ### end Alembic commands ###
