# Copyright 2026 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

"""add prereq field to course descriptions

Revision ID: f31ddd9f5ced
Revises: 140915d317a6
Create Date: 2022-10-14 23:07:25.181299+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f31ddd9f5ced'
down_revision = '140915d317a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swscourse', sa.Column('prereq_string', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swscourse', 'prereq_string')
    # ### end Alembic commands ###
